### ISSUE TITLE
Plugin should display warning or info message in case VM is not started

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#22]
_From @hferentschik on November 19, 2015 10:27_

If you run `vagrant adbinfo` when the VM has not been started yet or halted, you get:

```
/Users/hardy/.vagrant.d/gems/gems/vagrant-adbinfo-0.0.5/lib/command.rb:37:in `block in execute': undefined method `[]' for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /Users/hardy/.vagrant.d/gems/gems/vagrant-adbinfo-0.0.5/lib/command.rb:33:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

The plugin should catch this case and just display something along the lines:

"adbinfo only available after VM has been started. Run 'vagrant up' first"

_Copied from original issue: projectatomic/vagrant-adbinfo#30_

**Comment by navidshaikh** [comment]
_From @optak on November 23, 2015 13:50_

I hit this issue too, and it was quite confusing, crash didn't help me find issue (VM not running). This can negatively affect user experience for new users.

**Comment by navidshaikh** [comment]
_From @hferentschik on November 23, 2015 14:18_

> This can negatively affect user experience for new users.

+1

**Comment by navidshaikh** [comment]
_From @hferentschik on December 17, 2015 10:8_

Can we add focus:devex here as well?
