### ISSUE TITLE
TypeError - no implicit conversion of nil into String for version 0.0.1

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#31]
I have just started with ADB and fired following command:
`sudo vagrant service-manager env docker`
I encountered with following error:

```
[budhram@dhcp35-83 adb]$ sudo vagrant plugin install vagrant-service-manager
Installing the 'vagrant-service-manager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-service-manager (0.0.1)'!
[budhram@dhcp35-83 adb]$ sudo vagrant service-manager env docker
/root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:43:in `initialize': no implicit conversion of nil into String (TypeError)
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:43:in `open'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:43:in `copy_from_box'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:93:in `block in execute_docker_info'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:55:in `execute_docker_info'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:17:in `execute'
    from /usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
    from /usr/share/vagrant/lib/vagrant/environment.rb:301:in `cli'
    from /usr/share/vagrant/bin/vagrant:179:in `<main>'
```

I could debug it but looking for quick response if someone had already gone through it.

**Comment by bexelbie** [comment]
Is your vagrant box running?

**Comment by bexelbie** [comment]
See #22

**Comment by brgnepal** [comment]
@bexelbie , I think it is not this issue as my vagrant box is running.

```
[budhram@dhcp35-83 adb]$ sudo vagrant status
Current machine states:

default                   running (libvirt)

The Libvirt domain is running. To stop this machine, you can run
`vagrant halt`. To destroy the machine, you can run `vagrant destroy`.
[budhram@dhcp35-83 adb]$ sudo vagrant service-manager env docker
/root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:43:in `initialize': no implicit conversion of nil into String (TypeError)
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:43:in `open'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:43:in `copy_from_box'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:93:in `block in execute_docker_info'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:55:in `execute_docker_info'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:17:in `execute'
    from /usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
    from /usr/share/vagrant/lib/vagrant/environment.rb:301:in `cli'
    from /usr/share/vagrant/bin/vagrant:179:in `<main>'
```

**Comment by concaf** [comment]
@budhrg @bexelbie 
Same issue!

`sudo vagrant up`
`sudo vagrant service-manager env docker` - fails

Workaround:
`sudo vagrant up`
`sudo vagrant adbinfo` - runs
`sudo vagrant service-manager env docker` - runs

**Comment by mohammedzee1000** [comment]
There must be something that adbinfo does that service-manager needs, so we need to make sure service-manager does that as well.
