### ISSUE TITLE
install-cli commands throws an error when trying to install Kubernetes CLI

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/vagrant-service-manager#312]
kubernetes throws error with vsm install-cli 

Steps to reproduce 
- Install latest gem build from master
- run `vagrant.exe service-manager install-cli kubernetes`

Error log  https://gist.github.com/naina-verma/8f82ffa0e0f0ee7261ad62063bb09755
if kubernetes support is not ready then it should not be shown in install-cli help.

**Comment by hferentschik** [comment]
```
$ vagrant.exe service-manager install-cli kubernetes
C:/Users/naina/.vagrant.d/gems/gems/vagrant-service-manager-1.1.0.1/lib/    vagrant-service-manager/installer.rb:11:in `const_get': uninitialized constant     VagrantPlugins::ServiceManager::ADBKubernetesBinaryHandler (NameError)
        from C:/Users/naina/.vagrant.d/gems/gems/vagrant-service-manager-1.1.0.1/lib    /vagrant-service-manager/installer.rb:11:in `initialize'
        from C:/Users/naina/.vagrant.d/gems/gems/vagrant-service-manager-1.1.0.1/lib    /vagrant-service-manager/command.rb:280:in `new'
        from C:/Users/naina/.vagrant.d/gems/gems/vagrant-service-manager-1.1.0.1/lib    /vagrant-service-manager/command.rb:280:in `block in execute_install_cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/    plugin/v2/command.rb:235:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/    plugin/v2/command.rb:229:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/    plugin/v2/command.rb:229:in `with_target_vms'
        from C:/Users/naina/.vagrant.d/gems/gems/vagrant-service-manager-1.1.0.1/lib    /vagrant-service-manager/command.rb:275:in `execute_install_cli'
        from C:/Users/naina/.vagrant.d/gems/gems/vagrant-service-manager-1.1.0.1/lib    /vagrant-service-manager/command.rb:162:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/    cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/    environment.rb:302:in `cli'
from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<    main>'
```
