### ISSUE TITLE
Plugin shouldn't crash: block in execute_docker_info: undefined method for nil:NilClass

### ISSUE THREAD

**Issue by tuxdna** [projectatomic/vagrant-service-manager#38]
With following vagrant file:

```
Vagrant.configure(2) do |config|
  config.vm.box = "projectatomic/adb"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
  end
end
```

Before starting the VM, i.e.:

```
$ vagrant status
Current machine states:

default                   not created (libvirt)

The Libvirt domain is not created. Run `vagrant up` to create it.
```

When we run this plugin:

```
$ vagrant plugin update service-manager
Updating plugins: service-manager. This may take a few minutes...
All plugins are up to date.


$ vagrant service-manager env docker
/home/saleem/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:59:in `block in execute_docker_info': undefined method `[]' for nil:NilClass (NoMethodError)
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /home/saleem/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:55:in `execute_docker_info'
    from /home/saleem/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:17:in `execute'
    from /usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
    from /usr/share/vagrant/lib/vagrant/environment.rb:301:in `cli'
    from /usr/share/vagrant/bin/vagrant:179:in `<main>'

```

Plugin should detect whether the VM is up or not, and display a message instead of showing a stack-trace.

**Comment by bexelbie** [comment]
@tuxdna I believe this is fixed by merged PR #33 - it is available in master - or when we do our next release.

**Comment by tuxdna** [comment]
@bexelbie  That looks good. When will it be released ?

**Comment by bexelbie** [comment]
@tuxdna probably Friday - Monday at the latest.

**Comment by tuxdna** [comment]
Thanks @bexelbie . Closing it against https://github.com/projectatomic/vagrant-service-manager/pull/33
